SELECT 
    tc.TABLE_NAME, 
    tc.COLUMN_NAME, 
    CASE 
        WHEN cons.CONSTRAINT_TYPE = 'P' THEN 'YES' 
        ELSE 'NO' 
    END AS IS_PRIMARY_KEY
FROM 
    ALL_TAB_COLUMNS tc
LEFT JOIN 
    ALL_CONS_COLUMNS cc ON tc.TABLE_NAME = cc.TABLE_NAME 
    AND tc.COLUMN_NAME = cc.COLUMN_NAME 
    AND tc.OWNER = cc.OWNER
LEFT JOIN 
    ALL_CONSTRAINTS cons ON cc.OWNER = cons.OWNER 
    AND cc.CONSTRAINT_NAME = cons.CONSTRAINT_NAME 
    AND cons.CONSTRAINT_TYPE = 'P'
WHERE 
    tc.OWNER = 'BASE' -- Replace with your actual schema name
    AND tc.TABLE_NAME IN (
    'TIDALARD',
	'TIDALARH',
	'TIDANMST',
	'TIDCACOF',
	'TIDCACOM',
	'TIDCAFAC',
	'TIDCAMFR',
	'TIDCAMST',
	'TIDCANOT',
	'TIDCAPUR',
	'TIDCAQLV',
	'TIDCASTD',
	'TIDCASTF',
	'TIDCASUB',
	'TIDCASUM',
	'TIDCMLTM',
	'TIDCVMFR',
	'TIDDOHOF',
	'TIDDOPRT',
	'TIDECPHY',
	'TIDEMTOL',
	'TIDENPHN',
	'TIDIMTRN',
	'TIDISMST',
	'TIDISQTY',
	'TIDMRCOM',
	'TIDMRDTL',
	'TIDMRMST',
	'TIDMRRQS',
	'TIDMRSTD',
	'TIDMSMST',
	'TIDOSMST',
	'TIDOSQTY',
	'TIDPEMFR',
	'TIDPERQM',
	'TIDPKMST',
	'TIDPKQTY',
	'TIDPKSTG',
	'TIDPOCRS',
	'TIDPOMFR',
	'TIDPONOT',
	'TIDPOSCD',
	'TIDPRCOM',
	'TIDPRSTD',
	'TIDQUBID',
	'TIDQUEXE',
	'TIDQUMFR',
	'TIDQUMST',
	'TIDQUNOT',
	'TIDQUSTK',
	'TIDQUSUB',
	'TIDQUVND',
	'TIDQUVNM',
	'TIDRCLIN',
	'TIDRCMST',
	'TIDRCQTY',
	'TIDRQHDR',
	'TIDRQMST',
	'TIDRQNOT',
	'TIDRQUTC',
	'TIDSUBLN',
	'TIDTFOPN',
	'TIDTRMST',
	'TIDUMXRF',
	'TIDUSHST',
	'TIDVNACT',
	'TIDVNAUD',
	'TIDVNCOM',
	'TIDVNHST',
	'TIDVNNOT',
	'TIDVNRDX',
	'TIDVNRTG',
	'TIDVNSTD',
	'TIDVNSUP',
	'TIDVNTNI',
	'TIDWHMST'
    ) -- Replace with your actual table names list
    AND cons.CONSTRAINT_TYPE IS NOT NULL
ORDER BY 
    tc.TABLE_NAME, 
    tc.COLUMN_ID;
