select kcu.TABLE_SCHEMA AS [SchemaName], 
       kcu.TABLE_NAME AS [TableName], 
	   kcu.COLUMN_NAME AS [ColumnName], 
	   kcu.CONSTRAINT_NAME AS [PK_name], 
	   kcu.ORDINAL_POSITION
  from INFORMATION_SCHEMA.TABLE_CONSTRAINTS as tc
  join INFORMATION_SCHEMA.KEY_COLUMN_USAGE as kcu
    on kcu.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
   and kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
   and kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA
   and kcu.TABLE_NAME = tc.TABLE_NAME
 where tc.CONSTRAINT_TYPE in ( 'PRIMARY KEY', 'UNIQUE'  ) 
 order by kcu.TABLE_SCHEMA, kcu.TABLE_NAME, kcu.ORDINAL_POSITION, kcu.CONSTRAINT_NAME ;